# These are supported funding model platforms

# GitHub Sponsors
# github: [bitjaru]

# Open Collective
# open_collective: # Replace with a single Open Collective username

# Patreon
# patreon: # Replace with a single Patreon username

# Custom links (up to 4)
custom:
  - "https://github.com/bitjaru/codesyncer-cli#-support-development"
